<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DebugType>embedded</DebugType>
        <IsWebConfigTransformDisabled>true</IsWebConfigTransformDisabled>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
        <NoWarn>NU1901,NU1902</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LiteDB" Version="5.0.21" />
        <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.14.0" />
        <PackageReference Include="FFMpegCore" Version="5.2.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.20" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Remove=".\wwwroot\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="install-ffmpeg.cmd">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>  
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include=".\wwwroot\**\*" Exclude=".\wwwroot\.vscode\**">
            <LogicalName>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
            <Link>wwwroot\%(RecursiveDir)\%(Filename)%(Extension)</Link>
        </EmbeddedResource>
    </ItemGroup>

</Project>
